// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL for migrations if DIRECT_DATABASE_URL is not available
    // Both should be set to Prisma Accelerate URLs in CI/CD environments
    url: process.env["DATABASE_URL"] || process.env["DIRECT_DATABASE_URL"] || "",
  },
});
