name: Test Deploy with 9 Jobs

on:
  workflow_dispatch:


concurrency:
  group: deployment-${{ github.ref }}
  cancel-in-progress: false
jobs:
  job1:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - run: echo "Job 1"

  job2:
    runs-on: [self-hosted, Linux, X64]
    needs: job1
    steps:
      - run: echo "Job 2"

  job3:
    runs-on: [self-hosted, Linux, X64]
    needs: [job1, job2]
    environment:
      name: staging
    steps:
      - run: echo "Job 3"

  job4:
    runs-on: [self-hosted, Linux, X64]
    needs: job3
    environment:
      name: staging
    steps:
      - run: echo "Job 4"

  job5:
    runs-on: ubuntu-latest
    needs: job4
    environment:
      name: production-approval
    steps:
      - run: echo "Job 5"

  job6:
    runs-on: [self-hosted, Linux, X64]
    needs: job5
    environment:
      name: production
    steps:
      - run: echo "Job 6"

  job7:
    runs-on: [self-hosted, Linux, X64]
    needs: job6
    environment:
      name: production
    steps:
      - run: echo "Job 7"

  job8:
    runs-on: [self-hosted, Linux, X64]
    needs: job7
    steps:
      - run: echo "Job 8"

  job9:
    runs-on: [self-hosted, Linux, X64]
    needs: [job7, job8]
    steps:
      - run: echo "Job 9"
